CREATE TABLE STUDENT_TBL_01
 ( STUDENT_NO INT(11) NOT NULL AUTO_INCREMENT,
 		STUDENT_NAME VARCHAR(20 ),
 		STUDENT_ADDR VARCHAR(100 ),
 		STUDENT_PHONE VARCHAR(14 ),
 		STUDENT_BIRTH DATE,
 		STUDENT_EMAIL VARCHAR(50 ),
 		STUDENT_ID VARCHAR(12 ),
 		STUDENT_PW VARCHAR(50 ),
 		PRIMARY KEY (STUDENT_NO)
 );